"""num

Revision ID: 097b8bab48ac
Revises: d253e4569ceb
Create Date: 2023-04-19 17:55:27.341389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '097b8bab48ac'
down_revision = 'd253e4569ceb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('texts',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('text', sa.VARCHAR(length=256), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('texts')
    # ### end Alembic commands ###
