"""num6

Revision ID: 520490e64acd
Revises: 34000fbc7430
Create Date: 2023-05-12 12:34:11.012981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '520490e64acd'
down_revision = '34000fbc7430'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculators',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('asic_id', sa.SmallInteger(), nullable=True),
    sa.Column('kolvo', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['asic_id'], ['asics.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('texts')
    op.add_column('users', sa.Column('start_id', sa.SmallInteger(), nullable=True))
    op.add_column('users', sa.Column('category_id', sa.SmallInteger(), nullable=True))
    op.add_column('users', sa.Column('brand_id', sa.SmallInteger(), nullable=True))
    op.add_column('users', sa.Column('model_id', sa.SmallInteger(), nullable=True))
    op.create_foreign_key(None, 'users', 'brands', ['brand_id'], ['id'], ondelete='NO ACTION')
    op.create_foreign_key(None, 'users', 'categories', ['category_id'], ['id'], ondelete='NO ACTION')
    op.create_foreign_key(None, 'users', 'models', ['model_id'], ['id'], ondelete='NO ACTION')
    op.create_foreign_key(None, 'users', 'start', ['start_id'], ['id'], ondelete='NO ACTION')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'model_id')
    op.drop_column('users', 'brand_id')
    op.drop_column('users', 'category_id')
    op.drop_column('users', 'start_id')
    op.create_table('texts',
    sa.Column('id', sa.SMALLINT(), server_default=sa.text("nextval('texts_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('is_published', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='texts_pkey')
    )
    op.drop_table('calculators')
    # ### end Alembic commands ###
