"""initial

Revision ID: ba6670ca2411
Revises: 
Create Date: 2023-05-22 10:18:11.898368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba6670ca2411'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('start',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('start_name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('category_name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('brand_name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('model_name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=5), nullable=True),
    sa.Column('cost_electricity', sa.VARCHAR(length=128), nullable=True),
    sa.Column('hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('potreb', sa.VARCHAR(length=128), nullable=True),
    sa.Column('komm', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('start_id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['start_id'], ['start.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('brands',
    sa.Column('category_id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('models',
    sa.Column('brand_id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('models')
    op.drop_table('brands')
    op.drop_table('categories')
    op.drop_table('users')
    op.drop_table('start')
    # ### end Alembic commands ###
