"""num1

Revision ID: bac4fbb162a2
Revises: e2ddb565d1ca
Create Date: 2023-05-03 14:05:24.305459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bac4fbb162a2'
down_revision = 'e2ddb565d1ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
