"""num

Revision ID: e2ddb565d1ca
Revises: da1f48a4c1a7
Create Date: 2023-05-02 15:39:11.843020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2ddb565d1ca'
down_revision = 'da1f48a4c1a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
